#!/bin/sh

PREREQ=""
prereqs()
{
    echo "$PREREQ"
}

case $1 in
prereqs)
    prereqs
    exit 0
    ;;
esac

. /scripts/functions

log_begin_msg "Starting Installer"

export TERM=linux
cd /installer

if command -v chvt >/dev/null 2>&1; then
  chvt 1
fi

if command -v setsid >/dev/null 2>&1; then
  unset IFS
  read -r console rest </proc/consoles
  if [ "${console}" = "tty0" ]; then
    console="tty1"
  fi
  setsid sh -c "exec ./main <>/dev/${console} 1>&0 2>&1"
else
  ./main </dev/console >/dev/console 2>&1
fi

panic "Installer unexpectedly exited."

exit 1
