#!/bin/sh

## Simple Debian Installer for Loongson Pi Edu
## Copyright (C) 2020 Peter Zhang <mbyzhang@outlook.com>
##
## This program comes with ABSOLUTELY NO WARRANTY; for details see COPYING.
## This is free software, and you are welcome to redistribute it
## under certain conditions; see COPYING for details.

SOURCE_DIR=/source
SOURCE_IMAGE_FILE="$SOURCE_DIR/filesystem.sqfs"
SOURCE_IMAGE_MD5SUM_FILE="$SOURCE_DIR/filesystem.md5sum"
TARGET_DIR=/target
LOG_FILE=/run/installer.log

USER_NAME=loongson
USER_PASS=loongson
ROOT_PASS=loongson

ROOTFS_TYPE=ext4
ROOTFS_MK_OPTS=
BOOT_FS_TYPE=ext3
BOOT_FS_MK_OPTS=
BOOT_FS_SIZE=128M
SWAP_SIZE=512M

WT_TITLE="Loongson Pi Edu Installer v0.1"
WT_HEIGHT=20
WT_HEIGHT_SM=10
WT_WIDTH=60
WT_MENU_HEIGHT=10

export NEWT_COLORS="root=white,black"

set -o pipefail

logged() {
  $@ >> $LOG_FILE 2>>$LOG_FILE
}

log() {
  echo $@ >> $LOG_FILE
}

wt_info() {
  log "$@"
  whiptail --infobox "$@" $WT_HEIGHT_SM $WT_WIDTH
}

wt_msg_info() {
  log "$@"
  whiptail --msgbox "$@" $WT_HEIGHT_SM $WT_WIDTH
}

wt_msg_error() {
  wt_msg_info "Error: $@"
}

wt_gauge_update_status() {
  log "$2"
  echo -e "XXX\n$1\n$2\nXXX"
}

SOURCE_DISK=
TARGET_DISK=

detect_and_mount_installation_media() {
  mkdir -p "$SOURCE_DIR"
  mkdir -p "$TARGET_DIR"
  wt_info "Detecting installation media..."
  CANDIDATES=$(lsblk -prno NAME,FSTYPE,MOUNTPOINT | awk -F '\ ' '($2=="vfat" || $2=="iso9660") && $3=="" {print $1}')
  log "Available disks:"
  log "$CANDIDATES"
  for disk in $CANDIDATES; do
    log "Trying to mount $disk..."
    mount -o ro $disk $SOURCE_DIR
    if [ ! $? -eq 0 ]; then
      continue
    fi
    log "Mounted. Looking for squashfs image and its md5sum..."
    if [ ! -f "$SOURCE_IMAGE_FILE" ] || [ ! -f "$SOURCE_IMAGE_MD5SUM_FILE" ] ; then
      umount $disk
      continue
    fi
    log "Image found. $disk is a valid installation media."
    SOURCE_DISK=$disk
    return 0
  done
  wt_msg_error "No valid installaion media available. Please check your USB disk."
  return 1
}

verify_image() {
  wt_info "Checking integrity of the installation image..."
  if ! (cd "$SOURCE_DIR" && md5sum -c -s "$SOURCE_IMAGE_MD5SUM_FILE"); then
    wt_msg_error "Invalid checksum. Is your installaion media corrupt?"
    return 1
  fi
  log "Integrity check passed."
  return 0
}

BOOT_FS_TARGET=
ROOTFS_TARGET=
SWAP_TARGET=

choose_target() {
  while true; do
    AWK_PROG='!index("'$SOURCE_DISK'", $1) && $4=="disk" && $5=="0" { ORS=" "; print $1 " " $2 "_[" $3 "] OFF" }'
    CANDIDATES="$(lsblk -prndo NAME,SIZE,MODEL,TYPE,RM | awk -F '\ ' "$AWK_PROG")"
    TARGET_DISK=$(whiptail --radiolist "Where should we install Loongson OS? Press Space to select and Enter to confirm." --cancel-button "Rescan" $WT_HEIGHT $WT_WIDTH $WT_MENU_HEIGHT $CANDIDATES 3>&1 1>&2 2>&3)
    if [ ! $? -eq 0 ] || [ "$TARGET_DISK" = "" ]; then
      continue
    fi

    log "Chosen target disk: $TARGET_DISK"
    whiptail --yesno "ALL DATA WILL BE DESTROYED ON $TARGET_DISK, CONTINUE?" --defaultno $WT_HEIGHT_SM $WT_WIDTH
    if [ $? -eq 1 ]; then
      continue
    fi
    BOOT_FS_TARGET=${TARGET_DISK}1
    ROOTFS_TARGET=${TARGET_DISK}2
    SWAP_TARGET=${TARGET_DISK}3
    return 0
  done
}



partition_and_format_target() {
  {
    wt_gauge_update_status 20 "Partitioning $TARGET_DISK..."
    logged parted -s -- "$TARGET_DISK" \
      mklabel msdos \
      mkpart primary 2048s "$BOOT_FS_SIZE" \
      mkpart primary "$BOOT_FS_SIZE" "-$SWAP_SIZE" \
      mkpart primary linux-swap "-$SWAP_SIZE" -1s || return 1
    partprobe "$TARGET_DISK"
    sleep 1
    if [ ! -b "$BOOT_FS_TARGET" ] || [ ! -b "$ROOTFS_TARGET" ] || [ ! -b "$SWAP_TARGET" ]; then
      log "Could not find the target partitions."
      return 2
    fi
    wt_gauge_update_status 40 "Creating root filesystem on $ROOTFS_TARGET..."
    logged "mkfs.$ROOTFS_TYPE" $ROOTFS_MK_OPTS "$ROOTFS_TARGET"  || return 5
    logged mount -t "$ROOTFS_TYPE" "$ROOTFS_TARGET" "$TARGET_DIR" || return 6
    wt_gauge_update_status 60 "Creating boot filesystem on $BOOT_FS_TARGET..."
    logged "mkfs.$BOOT_FS_TYPE" "$BOOT_FS_MK_OPTS" "$BOOT_FS_TARGET" || return 3
    mkdir -p "$TARGET_DIR/boot"
    logged mount -t "$BOOT_FS_TYPE" "$BOOT_FS_TARGET" "$TARGET_DIR/boot" || return 4
    wt_gauge_update_status 80 "Creating swap on $SWAP_TARGET..."
    logged mkswap "$SWAP_TARGET" || return 7
  } | whiptail --gauge "Partitioning..." $WT_HEIGHT_SM $WT_WIDTH 0
  RET=$?
  if [ ! $RET -eq 0 ]; then
    wt_msg_error "code $RET"
    return 1
  fi
  return 0
}

unpack_filesystem() {
  LD_PRELOAD="/usr/lib/isatty.so" unsquashfs -f -d "$TARGET_DIR" "$SOURCE_IMAGE_FILE" 2>>$LOG_FILE | \
    tr '\r' '\n' | \
    awk '$NF ~ /%$/{ print substr($NF, 1, length($NF)-1) }' | \
    whiptail --gauge "Unpacking image to $TARGET_DISK..." $WT_HEIGHT_SM $WT_WIDTH 0
  if [ ! $? -eq 0 ]; then
    wt_msg_error "Failed to unpack image to $TARGET_DISK."
    return 1
  fi
  wt_info "Synchorizing changes... This may take a while"
  sync
  return 0
}

post_inst_add_user() {
  log "Changing root password..."
  echo "root:$ROOT_PASS" | logged chroot "$TARGET_DIR" chpasswd
  if [ ! $? -eq 0 ]; then
    wt_msg_error "Failed to update root password."
    return 1
  fi
  log "Adding user..."
  logged chroot "$TARGET_DIR" useradd -m "$USER_NAME" -s "/bin/bash"
  RET=$?
  if [ $RET -eq 9 ]; then
    log "User $USER_NAME already exists, skipping user creation"
  elif [ ! $RET -eq 0 ]; then
    wt_msg_error "Failed to create the user account."
    return 1
  fi
  log "Changing user $USER_NAME password..."
  echo "$USER_NAME:$USER_PASS" | logged chroot "$TARGET_DIR" chpasswd
  if [ ! $? -eq 0 ]; then
    wt_msg_error "Failed to update $USER_NAME password."
    return 1
  fi
  return 0
}

post_inst_configure_boot() {
  log "Configuring /etc/fstab..."
  ROOTFS_UUID=$(lsblk -no UUID "$ROOTFS_TARGET")
  BOOT_FS_UUID=$(lsblk -no UUID "$BOOT_FS_TARGET")
  SWAP_UUID=$(lsblk -no UUID "$SWAP_TARGET")
  if [ "$ROOTFS_UUID" = "" ] || [ "$BOOT_FS_UUID" = "" ] || [ "$SWAP_UUID" = "" ]; then
    wt_msg_error "Unable to determine filesystem UUIDs."
    return 1
  fi
  FSTAB_FILE="$TARGET_DIR/etc/fstab"
  echo "# GENERATED BY LOONGSON SIMPLE INSTALLER" > "$FSTAB_FILE"
  echo "UUID=$ROOTFS_UUID	/	$ROOTFS_TYPE	errors=remount-ro 0 1" >> "$FSTAB_FILE"
  echo "UUID=$BOOT_FS_UUID	/boot	$BOOT_FS_TYPE	defaults 0 1" >> "$FSTAB_FILE"
  echo "UUID=$SWAP_UUID		none	swap		sw 0 0" >> "$FSTAB_FILE"

  log "Configuring PMON..."
  if logged chroot "$TARGET_DIR" which pmon-update; then
    log "Found pmon-update, running"
    logged chroot "$TARGET_DIR" pmon-update
    if [ ! $? -eq 0 ]; then
      wt_msg_error "pmon-update failed."
      return 1
    fi
  else
    log 'Could not find pmon-update, skipping PMON configuration.'
  fi
  return 0
}

post_inst_regenerate_sshd_keys() {
  log "Regenerating SSH server keys..."
  if ! logged chroot "$TARGET_DIR" which sshd; then
    log "SSH server not found, skipping key generation..."
    return 0
  fi
  logged chroot "$TARGET_DIR" dpkg-reconfigure openssh-server
  if [ ! $? -eq 0 ]; then
    wt_msg_error "Failed to regenerate SSH server keys."
    return 1
  fi
  return 0
}

post_inst_setup_machine_id() {
  if ! logged chroot "$TARGET_DIR" which systemd-machine-id-setup; then
    log "systemd-machine-id-setup not found, skipping machine-id generation..."
    return 0
  fi
  logged chroot "$TARGET_DIR" systemd-machine-id-setup
  if [ ! $? -eq 0 ]; then
    wt_msg_error "Failed to setup machine-id."
    return 1
  fi
  return 0
}

post_installation() {
  wt_info "Running post-installation script..."
  post_inst_configure_boot && post_inst_add_user && post_inst_regenerate_sshd_keys && post_inst_setup_machine_id || return 1
}

umount_all() {
  if [ ! "$SOURCE_DISK" = "" ]; then
    umount "$SOURCE_DIR"
    SOURCE_DISK=
  fi

  if [ ! "$TARGET_DISK" = "" ]; then
    umount "$TARGET_DIR/boot"
    umount "$TARGET_DIR"
    TARGET_DISK=
  fi
}

do_install() {
  if [ -f "$LOG_FILE" ]; then
    mv -f "$LOG_FILE" "$LOG_FILE~"
  fi

  trap umount_all EXIT
  detect_and_mount_installation_media && \
  verify_image && \
  choose_target && \
  partition_and_format_target && \
  unpack_filesystem && \
  post_installation
  if [ ! $? -eq 0 ]; then
    umount_all
    whiptail --yesno "Installation failed. View log?" --defaultno $WT_HEIGHT_SM $WT_WIDTH
    if [ $? -eq 0 ]; then
      whiptail --textbox --scrolltext --title "Log file" $LOG_FILE $WT_HEIGHT $WT_WIDTH
    fi
    return 1
  fi
  umount_all
  wt_msg_info "Installation completed successfully. Remove the installation media and press Ok to reboot."
  do_reboot
}

do_shell() {
  clear
  ash
}

do_reboot() {
  reboot -f
}

do_shutdown() {
  poweroff -f
}

while true; do
  FUN=$(whiptail --title "$WT_TITLE" \
                 --menu "Welcome to Loongson Pi Edu Installer" $WT_HEIGHT $WT_WIDTH $WT_MENU_HEIGHT \
                 "1 Install" "Install Loongson OS to this machine" \
                 "2 Shell" "Enter rescue shell" \
                 "3 Reboot" "Restart this machine" \
                 "4 Shutdown" "Power off this machine" \
                 3>&1 1>&2 2>&3)
  RET=$?
  if [ $RET -eq 0 ]; then
    case "$FUN" in
      1\ *) do_install ;;
      2\ *) do_shell ;;
      3\ *) do_reboot ;;
      4\ *) do_shutdown ;;
      *) wt_msg_error "Unrecognized option" ;;
    esac
  else
    exit 0
  fi
done
