#!/bin/sh

set -e

PREREQ=""
prereqs()
{
    echo "$PREREQ"
}

case $1 in
prereqs)
    prereqs
    exit 0
    ;;
esac

. /usr/share/initramfs-tools/hook-functions

check_file_or_fail()
{
  if [ ! -f $1 ]; then
    echo "Error: Could not find file $1."
    exit 1
  fi
}

EXEC_DEPS="whiptail unsquashfs parted lsblk mkfs.vfat mkfs.ext4 mkfs.ext3 mkfs.ext2" # dmidecode

for exec in $EXEC_DEPS; do
  EXEC_PATH=$(which "$exec")
  if [ ! $? -eq 0 ]; then
    echo "Error: unable to find executable $exec"
    exit 1
  fi
  copy_exec "$EXEC_PATH" $(dirname "$EXEC_PATH")
done

INSTALLER_PREFIX="/usr/share/initramfs-tools/installer"
INSTALLER_FILES="main config"

mkdir "$DESTDIR/installer"
for file in $INSTALLER_FILES; do
  check_file_or_fail "$INSTALLER_PREFIX/$file"
  cp -f "$INSTALLER_PREFIX/$file" "$DESTDIR/installer"
done

MISC_FILES="/usr/lib/terminfo/l/linux"

for file in $MISC_FILES; do
  check_file_or_fail "$file"
  mkdir -p "$DESTDIR/$(dirname $file)"
  cp -f "$file" "$DESTDIR/$file"
done

manual_add_modules vfat nls_cp437 nls_ascii isofs

ISATTY_LIB_PRECOMPILED="/usr/share/initramfs-tools/lib/isatty.$(uname -m).so"
ISATTY_LIB_TARGET=

if [ -f "$ISATTY_LIB_PRECOMPILED" ]; then
  echo "Found precompiled binary of isatty.so"
  ISATTY_LIB_TARGET="$ISATTY_LIB_PRECOMPILED"
else
  echo "Precompiled binary of isatty.so not found, compiling..."
  ISATTY_LIB_TARGET="$(mktemp)"
  echo "int isatty(int fd) { return 1; }" | gcc -O2 -fpic -shared -ldl -o "$ISATTY_LIB_TARGET" -xc -
fi

copy_exec "$ISATTY_LIB_TARGET" /usr/lib/isatty.so

#rm -f "$ISATTY_LIB_TARGET"

exit 0
